# Generated by Django 5.0.3 on 2024-03-19 10:12

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('DR', 'DRAFT'), ('RJ', 'REJECTED'), ('PB', 'PUBLISHED')], default='DR', max_length=120),
        ),
    ]
