# Generated by Django 5.0.1 on 2024-04-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_rename_image_image_image_file_alter_image_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mehdi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('DR', 'DRAFT'), ('PB', 'PUBLISHED'), ('RE', 'REJECTED')], max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('DR', 'DRAFT'), ('RJ', 'REJECTED'), ('PB', 'PUBLISHED')], default='PB', max_length=120),
        ),
    ]
